import type { InstrumentDefinition, InstrumentCategoryMeta } from "./types";

// Import existing voices (reuse exact behavior)
import { playVoice as _playOriginal } from "../voices";

// Import new voices
import { voiceCelesta } from "./voices/keys";
import { voiceSynthLead, voiceChoir } from "./voices/synths";
import {
  voiceElectricClean,
  voiceElectricDistorted,
  voiceAcousticStrum,
  voiceAcousticFingerpick,
} from "./voices/guitars";
import {
  voicePanFlute,
  voiceAccordion,
  voiceSitar,
  voiceHarmonica,
  voiceOboe,
  voiceElectricViolin,
  voiceHarp,
  voiceMarimba,
  voiceVibraphone,
} from "./voices/world";
import { voiceElectricBass, voiceUprightBass } from "./voices/bass";
import {
  voiceOrchestraStrings,
  voiceBrass,
  voiceTrombone,
  voiceFlute,
} from "./voices/orchestral";

// Wrappers for existing voices that route through the original switch
function wrapOriginal(id: string) {
  return (freq: number, t: number, dur: number) => _playOriginal(id, freq, t, dur);
}

export const INSTRUMENT_CATEGORIES: InstrumentCategoryMeta[] = [
  { id: "keys",       label: "Keys",       color: "#FFD166", icon: "\u2B1C" },
  { id: "synths",     label: "Synths",     color: "#FF6B9D", icon: "\u25C8" },
  { id: "guitars",    label: "Guitars",    color: "#F97316", icon: "\u25CB" },
  { id: "world",      label: "World",      color: "#06D6A0", icon: "\u25CE" },
  { id: "bass",       label: "Bass",       color: "#4ECDC4", icon: "\u25C9" },
  { id: "orchestral", label: "Orchestral", color: "#A855F7", icon: "\u25EC" },
];

export const INSTRUMENT_DEFINITIONS: InstrumentDefinition[] = [
  // ─── KEYS (3) ───
  {
    id: "piano",
    label: "Piano",
    icon: "\u2B1C",
    category: "keys",
    color: "#FFD166",
    polyphonic: true,
    busTarget: "instrument",
    midiRange: [21, 108],
    defaultADSR: { attack: 0.005, decay: 0.12, sustain: 0.08, release: 1.8 },
    articulation: "struck",
    genreAffinity: ["jazz", "gospel", "soul", "rnb", "lofi", "hiphop"],
    moodAffinity: ["smooth", "chill", "uplifting", "sad"],
    description: "Acoustic grand piano with hammer transient and damping",
    play: wrapOriginal("piano"),
  },
  {
    id: "epiano",
    label: "Rhodes",
    icon: "\u25C6",
    category: "keys",
    color: "#84CC16",
    polyphonic: true,
    busTarget: "instrument",
    midiRange: [36, 96],
    defaultADSR: { attack: 0.007, decay: 0.1, sustain: 0.15, release: 0.35 },
    articulation: "struck",
    genreAffinity: ["jazz", "soul", "rnb", "lofi", "gospel", "funk"],
    moodAffinity: ["smooth", "chill", "warm"],
    description: "Rhodes electric piano with FM synthesis and tremolo",
    play: wrapOriginal("epiano"),
  },
  {
    id: "celesta",
    label: "Celesta",
    icon: "\u2728",
    category: "keys",
    color: "#C4B5FD",
    polyphonic: true,
    busTarget: "instrument",
    midiRange: [60, 108],
    defaultADSR: { attack: 0.003, decay: 0.3, sustain: 0.02, release: 0.5 },
    articulation: "struck",
    genreAffinity: ["lofi", "ambient"],
    moodAffinity: ["dreamy", "chill", "ethereal"],
    description: "Metallic bell-like keyboard with inharmonic partials",
    play: voiceCelesta,
  },

  // ─── SYNTHS (3) ───
  {
    id: "synth",
    label: "Synth Lead",
    icon: "\u25C8",
    category: "synths",
    color: "#FF6B9D",
    polyphonic: true,
    busTarget: "instrument",
    midiRange: [36, 96],
    defaultADSR: { attack: 0.08, decay: 0.2, sustain: 0.5, release: 0.25 },
    articulation: "sustained",
    genreAffinity: ["trap", "drill", "hiphop", "house", "funk"],
    moodAffinity: ["dark", "aggressive", "energetic"],
    description: "Detuned sawtooth lead with resonant filter sweep",
    play: wrapOriginal("synth"),
  },
  {
    id: "pad",
    label: "Synth Pad",
    icon: "\u25CE",
    category: "synths",
    color: "#A855F7",
    polyphonic: true,
    busTarget: "instrument",
    midiRange: [36, 96],
    defaultADSR: { attack: 1.2, decay: 0.5, sustain: 0.45, release: 2.0 },
    articulation: "sustained",
    genreAffinity: ["lofi", "ambient", "rnb", "trap"],
    moodAffinity: ["chill", "dreamy", "sad", "ethereal"],
    description: "Warm detuned pad with slow attack and long release",
    play: wrapOriginal("pad"),
  },
  {
    id: "choir",
    label: "Choir Pad",
    icon: "\u266A",
    category: "synths",
    color: "#EC4899",
    polyphonic: true,
    busTarget: "instrument",
    midiRange: [48, 84],
    defaultADSR: { attack: 1.0, decay: 0.3, sustain: 0.4, release: 2.0 },
    articulation: "sustained",
    genreAffinity: ["gospel", "ambient", "soul"],
    moodAffinity: ["uplifting", "ethereal", "warm"],
    description: "Vocal formant synthesis with parallel bandpass filters",
    play: voiceChoir,
  },

  // ─── GUITARS (4) ───
  {
    id: "electric_clean",
    label: "Clean Guitar",
    icon: "\u2606",
    category: "guitars",
    color: "#F97316",
    polyphonic: true,
    busTarget: "instrument",
    midiRange: [40, 88],
    defaultADSR: { attack: 0.002, decay: 0.3, sustain: 0.1, release: 0.5 },
    articulation: "plucked",
    genreAffinity: ["jazz", "soul", "rnb", "funk", "lofi"],
    moodAffinity: ["smooth", "chill", "warm"],
    description: "Clean electric guitar via Karplus-Strong synthesis",
    play: voiceElectricClean,
  },
  {
    id: "electric_distorted",
    label: "Distorted Guitar",
    icon: "\u26A1",
    category: "guitars",
    color: "#DC2626",
    polyphonic: true,
    busTarget: "instrument",
    midiRange: [40, 88],
    defaultADSR: { attack: 0.002, decay: 0.5, sustain: 0.3, release: 0.5 },
    articulation: "plucked",
    genreAffinity: ["drill", "trap"],
    moodAffinity: ["aggressive", "dark", "energetic"],
    description: "Overdriven electric guitar with waveshaper distortion",
    play: voiceElectricDistorted,
  },
  {
    id: "acoustic_strum",
    label: "Acoustic Strum",
    icon: "\u25D4",
    category: "guitars",
    color: "#D97706",
    polyphonic: true,
    busTarget: "instrument",
    midiRange: [40, 84],
    defaultADSR: { attack: 0.002, decay: 0.4, sustain: 0.05, release: 0.5 },
    articulation: "strummed",
    genreAffinity: ["soul", "gospel", "folk", "lofi"],
    moodAffinity: ["warm", "uplifting", "chill"],
    description: "Staggered multi-string acoustic strum",
    play: voiceAcousticStrum,
  },
  {
    id: "acoustic_fingerpick",
    label: "Fingerpick",
    icon: "\u25CC",
    category: "guitars",
    color: "#CA8A04",
    polyphonic: true,
    busTarget: "instrument",
    midiRange: [40, 84],
    defaultADSR: { attack: 0.002, decay: 0.3, sustain: 0.05, release: 0.4 },
    articulation: "plucked",
    genreAffinity: ["lofi", "jazz", "folk", "soul"],
    moodAffinity: ["chill", "smooth", "warm"],
    description: "Gentle single-note acoustic fingerpick",
    play: voiceAcousticFingerpick,
  },

  // ─── WORLD (9) ───
  {
    id: "pan_flute",
    label: "Pan Flute",
    icon: "\u2742",
    category: "world",
    color: "#06D6A0",
    polyphonic: true,
    busTarget: "instrument",
    midiRange: [60, 96],
    defaultADSR: { attack: 0.15, decay: 0.1, sustain: 0.35, release: 0.4 },
    articulation: "blown",
    genreAffinity: ["ambient", "lofi"],
    moodAffinity: ["chill", "dreamy", "ethereal"],
    description: "Breathy pan flute with vibrato and noise excitation",
    play: voicePanFlute,
  },
  {
    id: "accordion",
    label: "Accordion",
    icon: "\u2261",
    category: "world",
    color: "#14B8A6",
    polyphonic: true,
    busTarget: "instrument",
    midiRange: [36, 96],
    defaultADSR: { attack: 0.04, decay: 0.1, sustain: 0.45, release: 0.1 },
    articulation: "sustained",
    genreAffinity: ["folk", "jazz"],
    moodAffinity: ["warm", "uplifting"],
    description: "Reed organ with detuned partials and tremolo",
    play: voiceAccordion,
  },
  {
    id: "sitar",
    label: "Sitar",
    icon: "\u273C",
    category: "world",
    color: "#F59E0B",
    polyphonic: true,
    busTarget: "instrument",
    midiRange: [48, 84],
    defaultADSR: { attack: 0.005, decay: 0.5, sustain: 0.1, release: 0.8 },
    articulation: "plucked",
    genreAffinity: ["ambient", "lofi"],
    moodAffinity: ["dreamy", "ethereal", "dark"],
    description: "Sitar with sympathetic resonances and buzz waveshaping",
    play: voiceSitar,
  },
  {
    id: "harmonica",
    label: "Harmonica",
    icon: "\u25AC",
    category: "world",
    color: "#0EA5E9",
    polyphonic: false,
    busTarget: "instrument",
    midiRange: [60, 96],
    defaultADSR: { attack: 0.05, decay: 0.1, sustain: 0.4, release: 0.2 },
    articulation: "blown",
    genreAffinity: ["soul", "folk", "jazz"],
    moodAffinity: ["warm", "sad", "smooth"],
    description: "Blues harmonica with breath noise and vibrato",
    play: voiceHarmonica,
  },
  {
    id: "oboe",
    label: "Oboe",
    icon: "\u2759",
    category: "world",
    color: "#6366F1",
    polyphonic: false,
    busTarget: "instrument",
    midiRange: [58, 91],
    defaultADSR: { attack: 0.06, decay: 0.1, sustain: 0.3, release: 0.15 },
    articulation: "blown",
    genreAffinity: ["jazz", "ambient"],
    moodAffinity: ["smooth", "sad", "ethereal"],
    description: "Double reed with narrow pulse wave and formant resonances",
    play: voiceOboe,
  },
  {
    id: "electric_violin",
    label: "E. Violin",
    icon: "\u266B",
    category: "world",
    color: "#8B5CF6",
    polyphonic: false,
    busTarget: "instrument",
    midiRange: [55, 103],
    defaultADSR: { attack: 0.2, decay: 0.1, sustain: 0.35, release: 0.4 },
    articulation: "bowed",
    genreAffinity: ["jazz", "soul", "rnb", "ambient"],
    moodAffinity: ["smooth", "sad", "dreamy"],
    description: "Electric violin with sawtooth tone and body resonance",
    play: voiceElectricViolin,
  },
  {
    id: "harp",
    label: "Harp",
    icon: "\u2E1A",
    category: "world",
    color: "#D4AF37",
    polyphonic: true,
    busTarget: "instrument",
    midiRange: [24, 103],
    defaultADSR: { attack: 0.003, decay: 0.5, sustain: 0.05, release: 1.2 },
    articulation: "plucked",
    genreAffinity: ["ambient", "lofi", "jazz"],
    moodAffinity: ["dreamy", "ethereal", "chill"],
    description: "Concert harp with sympathetic resonance and long release",
    play: voiceHarp,
  },
  {
    id: "marimba",
    label: "Marimba",
    icon: "\u2503",
    category: "world",
    color: "#EA580C",
    polyphonic: true,
    busTarget: "instrument",
    midiRange: [45, 96],
    defaultADSR: { attack: 0.002, decay: 0.3, sustain: 0.02, release: 0.2 },
    articulation: "struck",
    genreAffinity: ["afrobeats", "jazz", "lofi"],
    moodAffinity: ["warm", "uplifting", "chill"],
    description: "Tuned bar percussion with inharmonic partials",
    play: voiceMarimba,
  },
  {
    id: "vibraphone",
    label: "Vibraphone",
    icon: "\u25C7",
    category: "world",
    color: "#7C3AED",
    polyphonic: true,
    busTarget: "instrument",
    midiRange: [53, 89],
    defaultADSR: { attack: 0.003, decay: 0.5, sustain: 0.15, release: 1.2 },
    articulation: "struck",
    genreAffinity: ["jazz", "lofi", "ambient"],
    moodAffinity: ["smooth", "chill", "dreamy"],
    description: "Metal bar vibraphone with motor tremolo vibrato",
    play: voiceVibraphone,
  },

  // ─── BASS (2) ───
  {
    id: "bass",
    label: "Bass",
    icon: "\u25C9",
    category: "bass",
    color: "#4ECDC4",
    polyphonic: false,
    busTarget: "bass",
    midiRange: [28, 67],
    defaultADSR: { attack: 0.003, decay: 0.2, sustain: 0.7, release: 0.1 },
    articulation: "sustained",
    genreAffinity: ["trap", "hiphop", "drill", "lofi", "rnb", "house"],
    moodAffinity: ["dark", "aggressive", "chill"],
    description: "Sine sub-bass with low-pass filtering",
    play: wrapOriginal("bass"),
  },
  {
    id: "electric_bass",
    label: "E. Bass",
    icon: "\u25A3",
    category: "bass",
    color: "#2DD4BF",
    polyphonic: false,
    busTarget: "bass",
    midiRange: [28, 67],
    defaultADSR: { attack: 0.005, decay: 0.25, sustain: 0.65, release: 0.15 },
    articulation: "plucked",
    genreAffinity: ["funk", "soul", "jazz", "rnb", "gospel"],
    moodAffinity: ["smooth", "warm", "energetic"],
    description: "Electric bass with harmonics and subtle overdrive",
    play: voiceElectricBass,
  },
  {
    id: "upright_bass",
    label: "Upright Bass",
    icon: "\u25D6",
    category: "bass",
    color: "#0D9488",
    polyphonic: false,
    busTarget: "bass",
    midiRange: [28, 62],
    defaultADSR: { attack: 0.015, decay: 0.3, sustain: 0.6, release: 0.2 },
    articulation: "plucked",
    genreAffinity: ["jazz", "soul", "gospel", "lofi"],
    moodAffinity: ["smooth", "warm", "chill"],
    description: "Warm upright bass with finger noise transient",
    play: voiceUprightBass,
  },

  // ─── ORCHESTRAL (4) ───
  {
    id: "organ",
    label: "Organ",
    icon: "\u2B21",
    category: "orchestral",
    color: "#F97316",
    polyphonic: true,
    busTarget: "instrument",
    midiRange: [36, 96],
    defaultADSR: { attack: 0.012, decay: 0.05, sustain: 0.5, release: 0.05 },
    articulation: "sustained",
    genreAffinity: ["gospel", "soul", "jazz", "funk"],
    moodAffinity: ["uplifting", "warm", "energetic"],
    description: "Drawbar organ with vibrato and harmonic series",
    play: wrapOriginal("organ"),
  },
  {
    id: "bells",
    label: "Bells",
    icon: "\u25EC",
    category: "orchestral",
    color: "#E879F9",
    polyphonic: true,
    busTarget: "instrument",
    midiRange: [60, 108],
    defaultADSR: { attack: 0.002, decay: 0.5, sustain: 0.02, release: 1.5 },
    articulation: "struck",
    genreAffinity: ["lofi", "ambient", "trap"],
    moodAffinity: ["dreamy", "chill", "ethereal"],
    description: "Tubular bells with inharmonic partials and stereo spread",
    play: wrapOriginal("bells"),
  },
  {
    id: "pluck",
    label: "Pluck",
    icon: "\u25C7",
    category: "orchestral",
    color: "#22D3EE",
    polyphonic: true,
    busTarget: "instrument",
    midiRange: [48, 96],
    defaultADSR: { attack: 0.003, decay: 0.3, sustain: 0.01, release: 0.55 },
    articulation: "plucked",
    genreAffinity: ["trap", "drill", "hiphop", "lofi"],
    moodAffinity: ["dark", "chill", "energetic"],
    description: "Fast-decay sawtooth pluck with filter darkening",
    play: wrapOriginal("pluck"),
  },
  {
    id: "synth_lead",
    label: "Synth Lead",
    icon: "\u25B2",
    category: "synths",
    color: "#F43F5E",
    polyphonic: false,
    busTarget: "instrument",
    midiRange: [48, 96],
    defaultADSR: { attack: 0.02, decay: 0.1, sustain: 0.3, release: 0.2 },
    articulation: "sustained",
    genreAffinity: ["trap", "drill", "house", "funk"],
    moodAffinity: ["aggressive", "energetic", "dark"],
    description: "Monophonic sawtooth+square lead with resonant filter LFO",
    play: voiceSynthLead,
  },
  {
    id: "orchestra_strings",
    label: "Strings",
    icon: "\u2248",
    category: "orchestral",
    color: "#B45309",
    polyphonic: true,
    busTarget: "instrument",
    midiRange: [36, 96],
    defaultADSR: { attack: 0.4, decay: 0.2, sustain: 0.35, release: 1.5 },
    articulation: "bowed",
    genreAffinity: ["gospel", "soul", "jazz", "ambient", "rnb"],
    moodAffinity: ["sad", "uplifting", "warm", "ethereal"],
    description: "Ensemble strings with 6 detuned sawtooths and slow attack",
    play: voiceOrchestraStrings,
  },
  {
    id: "brass",
    label: "Brass",
    icon: "\u2622",
    category: "orchestral",
    color: "#B91C1C",
    polyphonic: true,
    busTarget: "instrument",
    midiRange: [36, 84],
    defaultADSR: { attack: 0.12, decay: 0.1, sustain: 0.38, release: 0.25 },
    articulation: "blown",
    genreAffinity: ["jazz", "funk", "gospel", "soul", "hiphop"],
    moodAffinity: ["energetic", "uplifting", "warm"],
    description: "Brass section with formant resonance and bloom attack",
    play: voiceBrass,
  },
  {
    id: "trombone",
    label: "Trombone",
    icon: "\u2780",
    category: "orchestral",
    color: "#9F1239",
    polyphonic: false,
    busTarget: "instrument",
    midiRange: [34, 77],
    defaultADSR: { attack: 0.08, decay: 0.1, sustain: 0.35, release: 0.3 },
    articulation: "blown",
    genreAffinity: ["jazz", "funk", "gospel"],
    moodAffinity: ["smooth", "warm", "energetic"],
    description: "Solo trombone with dual formants and delayed vibrato",
    play: voiceTrombone,
  },
  {
    id: "flute",
    label: "Flute",
    icon: "\u2740",
    category: "orchestral",
    color: "#7E22CE",
    polyphonic: false,
    busTarget: "instrument",
    midiRange: [60, 96],
    defaultADSR: { attack: 0.08, decay: 0.1, sustain: 0.33, release: 0.3 },
    articulation: "blown",
    genreAffinity: ["jazz", "ambient", "lofi"],
    moodAffinity: ["smooth", "dreamy", "chill"],
    description: "Orchestral flute with breath noise and vibrato",
    play: voiceFlute,
  },
];
